### ISSUE TITLE
Not getting compiled

### ISSUE THREAD

**Issue by srirambadri** [olmerg/vilma_ma#1]
Hi,

Are you able to run the code.

I'm  not able to compile it properly. I keep getting an error:

/vilma_MA_ROS.cpp:32:3: error: ‘String’ was not declared in this scope
   String ma_ip;
   ^
then i changed the type to std::string but then I get the following error.

/vilma_MA_ROS.cpp:35:67: error: no matching function for call to ‘ros::NodeHandle::param(const char [19], std::string&, const char [14])’
  this->rosNode->param("microautobox/ma_ip", ma_ip, "192.168.140.3");

I'm not able to find the definition of the function. Can you please suggest what I should do?

**Comment by olmerg** [comment]
https://gitlab.com/vilma_unicamp/vilma_ma_ros/blob/master/src/vilma_ma_ros_node.cpp

The name of the file that you said is not correct

Look line 311
this-> rosNode.param < std:: string> ( "microautobox/ma_ip

**Comment by srirambadri** [comment]
i'm not able to open the link

page not found.

The code which is available here has the file vilma_MA_ROS.cpp.

There is no file with the name vilma_ma_ros_node.cpp as you have suggested!!

**Comment by olmerg** [comment]
Ok, I am sorry the code was moved to gitlab, If you are interested to connect to a microautobox, I can share my code and share the code of the blocks in  simulink. Please write me an email and I can give you access to the code in gitlab olmerg at gmail.com

**Comment by srirambadri** [comment]
thanks. I've sent you a mail!
